/*
 * configs.c
 *
 *  Created on: Apr 26, 2019
 *      Author: Szilard
 */

#include "configs.h"

void filter_cfg()
{
	Xil_Out32(APB_BASE_ADDR + CFG_IMG_WIDTH_ADDR, IMG_W);
	Xil_Out32(APB_BASE_ADDR + CFG_IMG_HEIGHT_ADDR, IMG_H);
	Xil_Out32(APB_BASE_ADDR + CFG_PIX_CORR_SEL_ADDR, 0);
	Xil_Out32(APB_BASE_ADDR + CFG_SHARP_SEL_ADDR, 0);
	Xil_Out32(APB_BASE_ADDR + CFG_SMOOTH_SEL_ADDR, 0);
	Xil_Out32(APB_BASE_ADDR + CFG_MEDIAN_SEL_ADDR, 0);
	Xil_Out32(APB_BASE_ADDR + CFG_LAPLACE_SEL_ADDR, 0);
	Xil_Out32(APB_BASE_ADDR + CFG_OUTPUT_SEL_ADDR, 0);
	Xil_Out32(APB_BASE_ADDR + CFG_PIX_CORR_THR_ADDR, 50);
	Xil_Out32(APB_BASE_ADDR + CFG_SHARP_COEF_ADDR, 50);
	Xil_Out32(APB_BASE_ADDR + CFG_TEST_MODE_EN_ADDR, 0);
}

void axi_rd_cfg()
{
	Xil_Out32(APB_BASE_ADDR + CFG_IMG_WIDTH_ADDR, IMG_W);
	Xil_Out32(APB_BASE_ADDR + CFG_IMG_HEIGHT_ADDR, IMG_H);
	Xil_Out32(APB_BASE_ADDR + CFG_STRIDE_ADDR, IMG_W);
	Xil_Out32(APB_BASE_ADDR + CFG_MAP0_BA_ADDR, TEST_IMG_R_ADDR);
	Xil_Out32(APB_BASE_ADDR + CFG_MAP1_BA_ADDR, TEST_IMG_G_ADDR);
	Xil_Out32(APB_BASE_ADDR + CFG_MAP2_BA_ADDR, TEST_IMG_B_ADDR);
	Xil_Out32(APB_BASE_ADDR + CFG_MAP0_EN_ADDR, 1);
	Xil_Out32(APB_BASE_ADDR + CFG_MAP1_EN_ADDR, 1);
	Xil_Out32(APB_BASE_ADDR + CFG_MAP2_EN_ADDR, 1);
	Xil_Out32(APB_BASE_ADDR + CFG_MAX_BURST_LENGTH_ADDR, 8);
	Xil_Out32(APB_BASE_ADDR + CFG_REVERSE_BYTE_ADDR, 0);
	Xil_Out32(APB_BASE_ADDR + CFG_INT_ACK_ADDR, 0);
	Xil_Out32(APB_BASE_ADDR + CFG_BLK_EN_ADDR, 0);
}

void enable_test()
{
	Xil_Out32(APB_BASE_ADDR + CFG_BLK_EN_ADDR, 0);
	Xil_Out32(APB_BASE_ADDR + CFG_TEST_MODE_EN_ADDR, 1);
	Xil_Out32(APB_BASE_ADDR + CFG_BLK_EN_ADDR, 1);
}
void disable_test()
{
	Xil_Out32(APB_BASE_ADDR + CFG_TEST_MODE_EN_ADDR, 0);
	Xil_Out32(APB_BASE_ADDR + CFG_BLK_EN_ADDR, 0);
}

void pix_corr_cfg()
{
	Xil_Out32(APB_BASE_ADDR + CFG_PIX_CORR_SEL_ADDR, PIX_CORR_IN_CODE);
	Xil_Out32(APB_BASE_ADDR + CFG_SHARP_SEL_ADDR, 0);
	Xil_Out32(APB_BASE_ADDR + CFG_SMOOTH_SEL_ADDR, 0);
	Xil_Out32(APB_BASE_ADDR + CFG_MEDIAN_SEL_ADDR, 0);
	Xil_Out32(APB_BASE_ADDR + CFG_LAPLACE_SEL_ADDR, 0);
	Xil_Out32(APB_BASE_ADDR + CFG_OUTPUT_SEL_ADDR, PIX_CORR_IN_CODE);
}
void smooth_cfg()
{
	Xil_Out32(APB_BASE_ADDR + CFG_PIX_CORR_SEL_ADDR, 0);
	Xil_Out32(APB_BASE_ADDR + CFG_SHARP_SEL_ADDR, 0);
	Xil_Out32(APB_BASE_ADDR + CFG_SMOOTH_SEL_ADDR, SMOOTH_IN_CODE);
	Xil_Out32(APB_BASE_ADDR + CFG_MEDIAN_SEL_ADDR, 0);
	Xil_Out32(APB_BASE_ADDR + CFG_LAPLACE_SEL_ADDR, 0);
	Xil_Out32(APB_BASE_ADDR + CFG_OUTPUT_SEL_ADDR, SMOOTH_IN_CODE);
}
void laplace_cfg()
{
	Xil_Out32(APB_BASE_ADDR + CFG_PIX_CORR_SEL_ADDR, 0);
	Xil_Out32(APB_BASE_ADDR + CFG_SHARP_SEL_ADDR, 0);
	Xil_Out32(APB_BASE_ADDR + CFG_SMOOTH_SEL_ADDR, 0);
	Xil_Out32(APB_BASE_ADDR + CFG_MEDIAN_SEL_ADDR, 0);
	Xil_Out32(APB_BASE_ADDR + CFG_LAPLACE_SEL_ADDR, LAPLACE_IN_CODE);
	Xil_Out32(APB_BASE_ADDR + CFG_OUTPUT_SEL_ADDR, LAPLACE_IN_CODE);
}
void median_cfg()
{
	Xil_Out32(APB_BASE_ADDR + CFG_PIX_CORR_SEL_ADDR, 0);
	Xil_Out32(APB_BASE_ADDR + CFG_SHARP_SEL_ADDR, 0);
	Xil_Out32(APB_BASE_ADDR + CFG_SMOOTH_SEL_ADDR, 0);
	Xil_Out32(APB_BASE_ADDR + CFG_MEDIAN_SEL_ADDR, MEDIAN_IN_CODE);
	Xil_Out32(APB_BASE_ADDR + CFG_LAPLACE_SEL_ADDR, 0);
	Xil_Out32(APB_BASE_ADDR + CFG_OUTPUT_SEL_ADDR, MEDIAN_IN_CODE);
}
void sharp_cfg()
{
	Xil_Out32(APB_BASE_ADDR + CFG_PIX_CORR_SEL_ADDR, 0);
	Xil_Out32(APB_BASE_ADDR + CFG_SHARP_SEL_ADDR, SHARP_IN_CODE);
	Xil_Out32(APB_BASE_ADDR + CFG_SMOOTH_SEL_ADDR, 0);
	Xil_Out32(APB_BASE_ADDR + CFG_MEDIAN_SEL_ADDR, 0);
	Xil_Out32(APB_BASE_ADDR + CFG_LAPLACE_SEL_ADDR, 0);
	Xil_Out32(APB_BASE_ADDR + CFG_OUTPUT_SEL_ADDR, SHARP_IN_CODE);
}

void smooth_laplace()
{
	Xil_Out32(APB_BASE_ADDR + CFG_PIX_CORR_SEL_ADDR, 0);
	Xil_Out32(APB_BASE_ADDR + CFG_SHARP_SEL_ADDR, 0);
	Xil_Out32(APB_BASE_ADDR + CFG_SMOOTH_SEL_ADDR, SMOOTH_IN_CODE);
	Xil_Out32(APB_BASE_ADDR + CFG_MEDIAN_SEL_ADDR, 0);
	Xil_Out32(APB_BASE_ADDR + CFG_LAPLACE_SEL_ADDR, SMOOTH_IN_CODE);
	Xil_Out32(APB_BASE_ADDR + CFG_OUTPUT_SEL_ADDR, LAPLACE_IN_CODE);

}
void smooth_sharp_laplace()
{
	Xil_Out32(APB_BASE_ADDR + CFG_PIX_CORR_SEL_ADDR, 0);
	Xil_Out32(APB_BASE_ADDR + CFG_SHARP_SEL_ADDR, SMOOTH_IN_CODE);
	Xil_Out32(APB_BASE_ADDR + CFG_SMOOTH_SEL_ADDR, SMOOTH_IN_CODE);
	Xil_Out32(APB_BASE_ADDR + CFG_MEDIAN_SEL_ADDR, 0);
	Xil_Out32(APB_BASE_ADDR + CFG_LAPLACE_SEL_ADDR, SHARP_IN_CODE);
	Xil_Out32(APB_BASE_ADDR + CFG_OUTPUT_SEL_ADDR, LAPLACE_IN_CODE);
}

void transparent_cfg()
{
	Xil_Out32(APB_BASE_ADDR + CFG_PIX_CORR_SEL_ADDR, 0);
	Xil_Out32(APB_BASE_ADDR + CFG_SHARP_SEL_ADDR, 0);
	Xil_Out32(APB_BASE_ADDR + CFG_SMOOTH_SEL_ADDR, 0);
	Xil_Out32(APB_BASE_ADDR + CFG_MEDIAN_SEL_ADDR, 0);
	Xil_Out32(APB_BASE_ADDR + CFG_LAPLACE_SEL_ADDR, 0);
	Xil_Out32(APB_BASE_ADDR + CFG_OUTPUT_SEL_ADDR, 0);
}

void switch_cfg(u8 sw_cfg)
{
	filter_cfg();
	axi_rd_cfg();
	switch(sw_cfg & 0x7)
	{
		case 0x01:
				 pix_corr_cfg();
				 break;
		case 0x02:
				smooth_cfg();
				break;
		case 0x03:
				laplace_cfg();
					break;
		case 0x04:
				median_cfg();
				break;
		case 0x05:
				sharp_cfg();
				break;
		case 0x06:
				smooth_laplace();
				break;
		case 0x07:
				smooth_sharp_laplace();
				break;
		default:
				transparent_cfg();
				break;
	}
}

