#set_false_path -from [get_cells -hierarchical -filter { NAME =~  "*ila_core_inst/u_ila_regs/reg_15/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg*" && IS_SEQUENTIAL }] -to [get_cells -hierarchical -filter { NAME =~ "*ila_core_inst/use_probe_debug_circuit_2_reg*" && IS_SEQUENTIAL}]
#set_false_path -from [get_cells -hierarchical -filter { NAME =~  "*ila_core_inst/u_ila_regs/reg_15/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg*" && IS_SEQUENTIAL }] -to [get_cells -hierarchical -filter { NAME =~ "*ila_core_inst/en_adv_trigger_2_reg*" && IS_SEQUENTIAL}]
#set_false_path -from [get_cells -hierarchical -filter { NAME =~  "*ila_core_inst/u_ila_regs/reg_1a/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg*" && IS_SEQUENTIAL }] -to [get_cells -hierarchical -filter { NAME =~ "*ila_core_inst/en_adv_trigger_2_reg*" && IS_SEQUENTIAL}]
#set_false_path -from [get_cells -hierarchical -filter { NAME =~  "*ila_core_inst/u_ila_reset_ctrl/asyncrounous_transfer.arm_in_transfer_inst/dout_reg*" && IS_SEQUENTIAL }] -to [get_cells -hierarchical -filter { NAME =~  "*ila_core_inst/u_ila_reset_ctrl/asyncrounous_transfer.arm_in_transfer_inst/temp_reg0_reg*" && IS_SEQUENTIAL }]
#set_false_path -from [get_cells -hierarchical -filter { NAME =~  "*ila_core_inst/u_ila_reset_ctrl/asyncrounous_transfer.halt_in_transfer_inst/dout_reg*" && IS_SEQUENTIAL }] -to [get_cells -hierarchical -filter { NAME =~  "*ila_core_inst/u_ila_reset_ctrl/asyncrounous_transfer.halt_in_transfer_inst/temp_reg0_reg*" && IS_SEQUENTIAL }]
#set_false_path -from [get_cells -hierarchical -filter { NAME =~  "*ila_core_inst/u_ila_reset_ctrl/asyncrounous_transfer.halt_out_transfer_inst/dout_reg*" && IS_SEQUENTIAL }] -to [get_cells -hierarchical -filter { NAME =~  "*ila_core_inst/u_ila_reset_ctrl/asyncrounous_transfer.halt_out_transfer_inst/temp_reg0_reg*" && IS_SEQUENTIAL }]
#set_false_path -from [get_cells -hierarchical -filter { NAME =~  "*ila_core_inst/u_ila_reset_ctrl/asyncrounous_transfer.arm_out_transfer_inst/dout_reg*" && IS_SEQUENTIAL }] -to [get_cells -hierarchical -filter { NAME =~  "*ila_core_inst/u_ila_reset_ctrl/asyncrounous_transfer.arm_out_transfer_inst/temp_reg0_reg*" && IS_SEQUENTIAL }]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 4096 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list system_i/clk_wiz_0/inst/clk_out2]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 40 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[0]} {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[1]} {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[2]} {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[3]} {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[4]} {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[5]} {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[6]} {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[7]} {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[8]} {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[9]} {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[10]} {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[11]} {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[12]} {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[13]} {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[14]} {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[15]} {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[16]} {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[17]} {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[18]} {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[19]} {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[20]} {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[21]} {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[22]} {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[23]} {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[24]} {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[25]} {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[26]} {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[27]} {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[28]} {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[29]} {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[30]} {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[31]} {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[32]} {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[33]} {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[34]} {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[35]} {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[36]} {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[37]} {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[38]} {system_i/MIPI_CSI_2_RX_0_m_axis_video_TDATA[39]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 24 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {system_i/axi_vdma_0/s_axis_s2mm_tdata[0]} {system_i/axi_vdma_0/s_axis_s2mm_tdata[1]} {system_i/axi_vdma_0/s_axis_s2mm_tdata[2]} {system_i/axi_vdma_0/s_axis_s2mm_tdata[3]} {system_i/axi_vdma_0/s_axis_s2mm_tdata[4]} {system_i/axi_vdma_0/s_axis_s2mm_tdata[5]} {system_i/axi_vdma_0/s_axis_s2mm_tdata[6]} {system_i/axi_vdma_0/s_axis_s2mm_tdata[7]} {system_i/axi_vdma_0/s_axis_s2mm_tdata[8]} {system_i/axi_vdma_0/s_axis_s2mm_tdata[9]} {system_i/axi_vdma_0/s_axis_s2mm_tdata[10]} {system_i/axi_vdma_0/s_axis_s2mm_tdata[11]} {system_i/axi_vdma_0/s_axis_s2mm_tdata[12]} {system_i/axi_vdma_0/s_axis_s2mm_tdata[13]} {system_i/axi_vdma_0/s_axis_s2mm_tdata[14]} {system_i/axi_vdma_0/s_axis_s2mm_tdata[15]} {system_i/axi_vdma_0/s_axis_s2mm_tdata[16]} {system_i/axi_vdma_0/s_axis_s2mm_tdata[17]} {system_i/axi_vdma_0/s_axis_s2mm_tdata[18]} {system_i/axi_vdma_0/s_axis_s2mm_tdata[19]} {system_i/axi_vdma_0/s_axis_s2mm_tdata[20]} {system_i/axi_vdma_0/s_axis_s2mm_tdata[21]} {system_i/axi_vdma_0/s_axis_s2mm_tdata[22]} {system_i/axi_vdma_0/s_axis_s2mm_tdata[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {system_i/axi_vdma_0/s_axis_s2mm_tuser[0]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list system_i/MIPI_CSI_2_RX_0_m_axis_video_TLAST]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list system_i/MIPI_CSI_2_RX_0_m_axis_video_TREADY]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list system_i/MIPI_CSI_2_RX_0_m_axis_video_TUSER]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list system_i/MIPI_CSI_2_RX_0_m_axis_video_TVALID]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list system_i/axi_vdma_0/s_axis_s2mm_tlast]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list system_i/axi_vdma_0/s_axis_s2mm_tready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list system_i/axi_vdma_0/s_axis_s2mm_tvalid]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
